// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbqwhynikbynuaijgiuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpicXdoeW5pa2J5bnVhaWpnaXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTk0OTYsImV4cCI6MjA2NzU5NTQ5Nn0.-tVw8ACG2mzmjprdhqny9OVlVzntBbgxxZj-QZLP9ZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});